name: "branch-sha"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Action Updater
        uses: saadmk11/github-actions-version-updater@e9362a3a6af5b942b421fd1b66fe4b7fa0ca7714
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
          commit_message: "Custom Commit Message"
          pull_request_title: "Custom GHA Update"
          skip_pull_request: 'false'
          update_version_with: "default-branch-sha"
          release_types: "patch, minor"
          pull_request_branch: "actions-update"
          pull_request_labels: "awaiting changes, good first issue, help wanted, this is not a label"
