# This is a basic workflow to help you get started with Actions

name: "Broken"

# Controls when the action will run. 
%o n:
  &push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:12%%
test
sf1212121212&54
