name: "default"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Action Updater
        uses: saadmk11/github-actions-version-updater@v0.7.3
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}
          committer_username: 'Test'
          committer_email: 'test@test.com'
          commit_message: 'Commit Message'
          pull_request_title: 'Pull Request Title'

