name: "default"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.FINE_GRAINED_TOEKN }}

      - name: Run GitHub Action Updater
        uses: saadmk11/github-actions-version-updater@main
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

