name: "branch-sha"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Action Updater
        uses: saadmk11/github-actions-version-updater@use-pydantic
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

